<div class="col-md-3">

    <div class="perfil">
        <div class="perfilTopo">

        </div>

        <div class="perfilPainel">

            <div class="row mt-2 mb-2">
                <div class="col mb-2">
                    <span class="perfilPainelNome"><?= $this->view->nome_usuario['nome'] ?></span>
                </div>
            </div>

            <div class="row mb-2">

                <div class="col">
                    <span class="perfilPainelItem">Tweets</span><br />
                    <span class="perfilPainelItemValor"><?= $this->view->total_tweets['total_tweets'] ?></span>
                </div>

                <div class="col">
                    <span class="perfilPainelItem">Seguindo</span><br />
                    <span class="perfilPainelItemValor"><?= $this->view->total_seguindo['total_seguindo'] ?></span>
                </div>

                <div class="col">
                    <span class="perfilPainelItem">Seguidores</span><br />
                    <span class="perfilPainelItemValor"><?= $this->view->total_seguidores['total_seguidores'] ?></span>
                </div>

            </div>

        </div>
    </div>

</div>