<nav class="navbar navbar-expand-lg menu">
	<div class="container">
		<div class="navbar-nav">
			<a class="menuItem" href="/timeline">
				Home
			</a>

			<a class="menuItem" href="/sair">
				Sair
			</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
		</div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">

		<?php require 'perfilBanner.phtml'; ?>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>

						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as $id_tweet => $tweet) { ?>

				<div class="row tweet">
					<div class="col">
						<p><strong><?= $tweet['nome'] ?></strong> <small class="text text-muted"><?= $tweet['data'] ?></small></p>
						<p><?= $tweet['tweet'] ?></p>

						<br />
						<?php if ($tweet['id_usuario'] == $_SESSION['id']) { ?>
							<form>
								<div class="col d-flex justify-content-end">
									<a href="/remover_tweet?id_tweet=<?= $tweet['id'] ?>" type="submit" class="btn btn-danger"><small>Remover</small></a>
								</div>
							</form>
						<?php } ?>
					</div>
				</div>

			<?php } ?>

			<?php if($this->view->total_paginas > 1) { ?>

				<div class="row mt-4 justify-content-center">
					<nav aria-label="pagination">
						<ul class="pagination">

							<?php if(isset($_GET['pag']) && $_GET['pag'] > 1) { ?>

								<li class="page-item">
									<a class="page-link" href="?pag=1" aria-label="Previous">
										<span aria-hidden="true">Primeira</span>
									</a>
								</li>

							<?php } ?>

							<?php for($i = 1; $i <= $this->view->total_paginas; $i++)  { ?>
							
								<li class="page-item <?=$this->view->pagina_atual == $i ? 'active' : '' ?>"><a class="page-link" href="?pag=<?=$i?>"><?=$i?></a></li>

							<?php } ?>

							<?php if(!isset($_GET['pag']) || isset($_GET['pag']) && $_GET['pag'] < $this->view->total_paginas) { ?>

								<li class="page-item">
									<a class="page-link" href="?pag=<?=$this->view->total_paginas?>" aria-label="Next">
										<span aria-hidden="true">Última</span>
									</a>
								</li>
							
							<?php } ?>

						</ul>
					</nav>
				</div>

			<?php } ?>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>